"""
Static universe of 50 non-stablecoin cryptocurrencies.
IDs match CoinGecko's coin identifiers.
"""

COIN_UNIVERSE = [
    ("bitcoin", "BTC"),
    ("ethereum", "ETH"),
    ("ripple", "XRP"),
    ("binancecoin", "BNB"),
    ("solana", "SOL"),
    ("dogecoin", "DOGE"),
    ("cardano", "ADA"),
    ("tron", "TRX"),
    ("chainlink", "LINK"),
    ("avalanche-2", "AVAX"),
    ("stellar", "XLM"),
    ("the-open-network", "TON"),
    ("shiba-inu", "SHIB"),
    ("sui", "SUI"),
    ("hedera-hashgraph", "HBAR"),
    ("polkadot", "DOT"),
    ("litecoin", "LTC"),
    ("bitcoin-cash", "BCH"),
    ("monero", "XMR"),
    ("uniswap", "UNI"),
    ("near", "NEAR"),
    ("aptos", "APT"),
    ("internet-computer", "ICP"),
    ("ethereum-classic", "ETC"),
    ("render-token", "RENDER"),
    ("vechain", "VET"),
    ("cosmos", "ATOM"),
    ("filecoin", "FIL"),
    ("arbitrum", "ARB"),
    ("optimism", "OP"),
    ("algorand", "ALGO"),
    ("aave", "AAVE"),
    ("maker", "MKR"),
    ("sei-network", "SEI"),
    ("kaspa", "KAS"),
    ("celestia", "TIA"),
    ("crypto-com-chain", "CRO"),
    ("injective-protocol", "INJ"),
    ("immutable-x", "IMX"),
    ("the-graph", "GRT"),
    ("fantom", "FTM"),
    ("lido-dao", "LDO"),
    ("jupiter-exchange-solana", "JUP"),
    ("ondo-finance", "ONDO"),
    ("worldcoin-wld", "WLD"),
    ("polygon-ecosystem-token", "POL"),
    ("pepe", "PEPE"),
    ("bonk", "BONK"),
    ("theta-token", "THETA"),
    ("the-sandbox", "SAND"),
]
